mysite/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:course_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:course_id>/', views.cart_remove, name='cart_remove'),
]

mysite/cources/urls.py
from django.urls import path
from . import views

app_name = 'cources'

urlpatterns = [
    path('',views.course_list,name='course_list'),
    path('<slug:category_slug>/', views.course_list, name='course_list_by_category'),
    path('<int:id>/<slug:slug>/', views.course_detail, name='course_detail'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import  path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace = 'orders')),
    path('payment/', include('payment.urls', namespace = 'payment')),
    path('',include('cources.urls', namespace= 'cources')),

    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name = 'order_create'),
]

mysite/payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name = 'process'),
    path('process/', views.payment_completed, name = 'completed'),
    path('canceled/', views.payment_canceled, name = 'canceled'),
    
    

]

mysite/cources/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('cources:course_list_by_category',
                       args=[self.slug])
    


class Course(models.Model):

    category = models.ForeignKey(Category, related_name='cources', on_delete=models.CASCADE, blank=True)
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='courses/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    stock = models.PositiveIntegerField()

    class Meta:
        ordering =('name',)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('cources:course_detail', args=[self.id, self.slug])
    

# Create your models here.

mysite/orders/models.py
from django.db import models
from cources.models import Course

class Order(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.EmailField()
    created = models.DateField(auto_now_add=True)
    update = models.DateField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering=['-created']

    def __str__(self):
        return f'Заказ {self.id}'
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name= 'items', on_delete=models.CASCADE)
    course = models.ForeignKey(Course,related_name= 'order_items', on_delete=models.CASCADE )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)
    
    def get_cost(self):
        return self.price*self.quantity

mysite/payment/models.py
from django.db import models

# Create your models here.

mysite/cart/forms.py
from django import forms  

COURSE_QUANTITY_CHOISES = [(i, str(i)) for i in range(1,10)]

class CartAddCourseForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=COURSE_QUANTITY_CHOISES, label = "Количество", coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

mysite/orders/forms.py
from django import forms 
from .models import Order

class OrderCreateForm(forms.ModelForm):
    
    class Meta:
        model = Order
        fields = ('first_name','last_name', 'email')
        labels = {'first_name':'Имя', 'last_name':'Фамилия', 'email':'email'}

mysite/cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from .cart import Cart
from cources.models import Course
from .forms import CartAddCourseForm

@require_POST
def cart_add(request, course_id):
    cart=Cart(request)
    course = get_object_or_404(Course, id = course_id)
    form = CartAddCourseForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(course=course, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, course_id):
    cart=Cart(request)
    course = get_object_or_404(Course, id = course_id)
    cart.remove(course)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart=Cart(request)
    return render(request, 'cart/detail.html', {'cart':cart})
# Create your views here.

mysite/cources/views.py
from django.shortcuts import render, get_object_or_404
from .models import Course, Category
from cart.forms import CartAddCourseForm

def course_list(request, category_slug = None):
    category = None
    categories = Category.objects.all()
    courses= Course.objects.filter(available = True)
    if category_slug:
        category = get_object_or_404(Category, slug = category_slug)
        courses = courses.filter(category = category)
    return render(request,
                  'cources/course/list.html',
                  {'courses':courses,
                   'category':category,
                   'categories':categories})

def course_detail(request, id, slug):
    course = get_object_or_404(Course, id=id, slug= slug, available = True)

    cart_course_form = CartAddCourseForm()
    return render(request,
                  'cources/course/detail.html',
                  {'course':course,
                   'cart_course_form':cart_course_form})
# Create your views here.

mysite/orders/views.py
from django.shortcuts import render
from cart.cart import Cart
from .forms import OrderCreateForm
from .models import OrderItem

# Create your views here.

def order_create(request):
    cart = Cart(request)
    if request.method =='POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         course = item ['course'],
                                         price = item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            return render(request,
                          'orders/order/created.html',
                          {'order':order})
    else:
        form = OrderCreateForm()
    return render(request,
                  'orders/order/create.html',
                  {'cart':cart, 'form':form})

mysite/payment/views.py
from django.shortcuts import render

def payment_process(request):
    return render(request, 'payment/process.html')

def payment_completed(request):
    return render(request, 'payment/completed.html')

def payment_canceled(request):
    return render(request, 'payment/canceled.html')

mysite/cart/templates/cart/detail.html
{% extends "cources/base.html" %}
{% load static %}
{%block title %}
Корзина
{% endblock %}

{% block content %}
<h1> Ваша корзина </h1>
<table class="cart">
    <thead>
        <tr>
           <th>Изображение</th>
           <th>Курс</th>
           <th>Количество</th>
           <th>Удалить</th>
           <th>Цена</th>
           <th>Стоимость</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart%}
        {% with course=item.course%}
        <tr>
            <td>
                <a href="{{course.get_absolute_url}}">
                    <img src="{% if course.image %}{{course.image.url}} {% else %} {% static "img/no_image.png" %} {% endif %}">
                </a>
            </td>
            <td> {{course.name}} </td>
            <td> {{item.quantity}} </td>
            <td>
                <form action="{% url "cart:cart_remove" course.id %}" method="post">
                    <input type="submit" value="Удалить">
                    {% csrf_token %}
                </form>
            </td>
            <td class="num"> {{item.price}} </td>
            <td class="num"> {{item.total_price}}</td>
        </tr>
    {% endwith%}
    {% endfor%}
    <tr class = "total">
        <td> Общая сумма </td>
        <td class="num">{{cart.get_total_price}}</td>
    </tr> 
</tbody>
</table>
<p class="text-right">
    <a href="{% url "cources:course_list" %}"> Продолжить покупки </a> 
    <a href = "{% url "orders:order_create" %}" class="button"> Сделать заказ </a>  
{% endblock %}

mysite/cources/templates/cources/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>
            {% block title %}Курсы гитары{% endblock %}
        </title>
        <link href="{% static "css/base.css" %}" rel ="stylesheet">
    </head>
<body>
    <div id="header">
        <a href="/" class = "logo"> Курсы гитары </a>
    </div>

    <div id="subheader">
        <div class="cart">
        {% with total_items=cart|length %}
        {% if total_items > 0 %}
        Ваша корзина:
        <a href="{%url "cart:cart_detail" %}">
            {{total_items}} курсов 
            {{cart.get_total_price}} руб
        </a>
        {% elif not order %}
        Ваша корзина пуста
        {% endif %}
        {% endwith %}
    </div>

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

mysite/cources/templates/cources/course/detail.html
{% extends "cources/base.html" %}
{% load static %}
{%block title %}
 {{course.name}} 
{% endblock %}

{% block content %}
<div class="course-detail">
    <img src="{% if course.image %}{{ course.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
    <h1>{{course.name}}</h1>
    <h2>
        <a href="{{course.category.get_absolute_url}}">
            {{course.category}}
        </a>
    </h2>
    <p class="price"> {{course.price}}</p>
    <form action="{% url "cart:cart_add" course.id %}" method ="post">
        {{cart_course_form}}
        {% csrf_token %}
        <input type="submit" value="Добавить в корзину">
    </form>    
    {{course.description|linebreaks}}
</div>
{% endblock %}

mysite/cources/templates/cources/course/list.html
{% extends "cources/base.html" %}
{% load static %}

{%block title %}
{% if category %} {{category.name}} {%else%} Курсы {% endif %}
{% endblock %}

{% block content %}
<div id = "sidebar">
    <h3> Категории </h3>
    <ul>
        <li {% if not category %} class = "selected" {% endif%}>
            <a href="{% url "cources:course_list" %}">Все курсы </a>
        </li>
        {% for c in categories%}
        <li {% if category.slug == c.slug%} class = "selected" {% endif%}>
            <a href="{{c.get_absolute_url}}">{{c.name}}</a>
        </li>
{% endfor %}
    </ul>
</div>

<div id ="main" class = "cources-list">
    <h1> {% if category%} {{category.name}} {%else%} Курсы {% endif %} </h1>
    {%for course in courses %}
    <div class = "item">
        <a href="{{course.get_absolute_url}}">
            <img src="{% if course.image %}{{ course.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href ="{{course.get_absolute_url}}"> {{course.name}} </a>
        <br> 
        {{course.price}}
    </div>
    {% endfor %}
</div>
{% endblock %}

mysite/orders/templates/orders/order/create.html
{% extends "cources/base.html" %}
{% block title %} Ваш заказ {% endblock %}

{% block content%}
<h1> Заказ </h1>
<div class="order-info">
    <h3> Ващ заказ </h3>
    <ul>
        {%for item in cart%}
        <li>
            {{item.quantity}}x{{item.course.name}}
            <span> {{item.total_price}} руб</span>
        </li>
        {% endfor %}
    </ul>
    <p> Итого: {{ cart.get_total_price}} руб </p>
</div>
<form method="post" class="order-form">
    {{form.as_p}}
    <p><input type="submit" value = "Отправить заказ"> </p>
    {% csrf_token %}
</form>
{% endblock %}

mysite/orders/templates/orders/order/created.html
{% extends "cources/base.html" %}
{% block title %} Спасибо за Ваш заказ {% endblock %}

{% block content%}
<h1> Спасибо! </h1>
<p> Ваш заказ успешно сформирован. Номер Вашего заказа <strong> {{order.id}}</strong>.</p>
{% endblock%}